#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : wtfhe_arm.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Aug 26 13:11:06 +0200 2021
# SW Build 2902540 on Wed May 27 19:54:49 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: wtfhe_arm.sh [-help]
# usage: wtfhe_arm.sh [-lib_map_path]
# usage: wtfhe_arm.sh [-noclean_files]
# usage: wtfhe_arm.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'wtfhe_arm.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_7 processing_system7_vip_v1_0_9 xil_defaultlib blk_mem_gen_v8_4_4 axi_bram_ctrl_v4_1_3 xlconstant_v1_1_7 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 smartconnect_v1_0 axi_register_slice_v2_1_21 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_gpio_v2_0_23 xbip_dsp48_wrapper_v3_0_4 xbip_utils_v3_0_10 xbip_pipe_v3_0_6 xbip_dsp48_macro_v3_0_17)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "wtfhe_arm.sh - Script generated by export_simulation (Vivado v2020.1 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "D:/Applications/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "D:/Applications/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "D:/Applications/Vivado/2020.1/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "D:/Applications/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "D:/Applications/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "D:/Applications/Vivado/2020.1/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "D:/Applications/Vivado/2020.1/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "D:/Applications/Vivado/2020.1/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "D:/Applications/Vivado/2020.1/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "D:/Applications/Vivado/2020.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "D:/Applications/Vivado/2020.1/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "D:/Applications/Vivado/2020.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "D:/Applications/Vivado/2020.1/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_7 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ce6c/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_9 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_processing_system7_0_0/sim/wtfhe_arm_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_blk_mem_gen_0_0/sim/wtfhe_arm_blk_mem_gen_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_bram_ctrl_v4_1_3 $vhdlan_opts \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/db86/hdl/axi_bram_ctrl_v4_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_bram_ctrl_0_0/sim/wtfhe_arm_axi_bram_ctrl_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/sim/bd_11e1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_0/sim/bd_11e1_one_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_1/sim/bd_11e1_psr_aclk_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/sc_util_v1_0_vl_rfs.sv" \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/c012/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_2/sim/bd_11e1_arsw_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_3/sim/bd_11e1_rsw_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_4/sim/bd_11e1_awsw_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_5/sim/bd_11e1_wsw_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_6/sim/bd_11e1_bsw_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/053f/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_7/sim/bd_11e1_s00mmu_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ca72/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_8/sim/bd_11e1_s00tr_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/9d43/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_9/sim/bd_11e1_s00sic_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/b89e/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_10/sim/bd_11e1_s00a2s_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_11/sim/bd_11e1_sarn_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_12/sim/bd_11e1_srn_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_13/sim/bd_11e1_sawn_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_14/sim/bd_11e1_swn_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_15/sim/bd_11e1_sbn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/7005/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_16/sim/bd_11e1_m00s2a_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_17/sim/bd_11e1_m00arn_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_18/sim/bd_11e1_m00rn_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_19/sim/bd_11e1_m00awn_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_20/sim/bd_11e1_m00wn_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_21/sim/bd_11e1_m00bn_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work smartconnect_v1_0 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/7af8/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_22/sim/bd_11e1_m00e_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_23/sim/bd_11e1_m01s2a_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_24/sim/bd_11e1_m01arn_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_25/sim/bd_11e1_m01rn_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_26/sim/bd_11e1_m01awn_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_27/sim/bd_11e1_m01wn_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_28/sim/bd_11e1_m01bn_0.sv" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/bd_0/ip/ip_29/sim/bd_11e1_m01e_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2ef9/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/6b56/hdl" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/2702/hdl/verilog" +incdir+"$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/4676/hdl/verilog" +incdir+"D:/Applications/Vivado/2020.1/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_smc_0/sim/wtfhe_arm_axi_smc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_rst_ps7_0_50M_0/sim/wtfhe_arm_rst_ps7_0_50M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_23 $vhdlan_opts \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ipshared/bb35/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_axi_gpio_0_0/sim/wtfhe_arm_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ip/wtfhe_arm_BOOTSTRAPPING_ARM_1_0/src/xbip_dsp48_macro_0_1/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ip/wtfhe_arm_BOOTSTRAPPING_ARM_1_0/src/xbip_dsp48_macro_0_1/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ip/wtfhe_arm_BOOTSTRAPPING_ARM_1_0/src/xbip_dsp48_macro_0_1/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_macro_v3_0_17 $vhdlan_opts \
    "$ref_dir/../../../../wtfhe.srcs/sources_1/bd/wtfhe_arm/ip/wtfhe_arm_BOOTSTRAPPING_ARM_1_0/src/xbip_dsp48_macro_0_1/hdl/xbip_dsp48_macro_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_BOOTSTRAPPING_ARM_1_0/src/xbip_dsp48_macro_0_1/sim/xbip_dsp48_macro_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts -vhdl08 \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/CONST.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/ACCUMULATOR.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/ADDR_REG.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/COUNTER.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/EXTENDED_COUNTER.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/EXTERNAL_PRODUCT.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/LATCH.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/LSM.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/MATRIX_ACC.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/MATRIX_MULT.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/MULT_CONTROLLER.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/NEGACYCLIC_MEM.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/POLY_ADD.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/POLY_EXP.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/POLY_MPX.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/POLY_MULT.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/POLY_REG.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/POLY_SPLIT.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/SAMPLE_EXTRACT.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/TLWE_REG.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/TLWE_ROUNDING.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/ipshared/2ee9/sources_1/new/BOOTSTRAPPING_ARM.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/wtfhe_arm/ip/wtfhe_arm_BOOTSTRAPPING_ARM_1_0/sim/wtfhe_arm_BOOTSTRAPPING_ARM_1_0.vhd" \
    "$ref_dir/../../../bd/wtfhe_arm/sim/wtfhe_arm.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.wtfhe_arm xil_defaultlib.glbl -o wtfhe_arm_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./wtfhe_arm_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./wtfhe_arm.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key wtfhe_arm_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc wtfhe_arm_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./wtfhe_arm.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: wtfhe_arm.sh [-help]\n\
Usage: wtfhe_arm.sh [-lib_map_path]\n\
Usage: wtfhe_arm.sh [-reset_run]\n\
Usage: wtfhe_arm.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
